# Application Name
spring.application.name=flicker

# Server Configuration - Default to 8080 for local
server.port=${PORT:8080}

# MongoDB Atlas Connection - Default to local Mongo instance for testing
spring.data.mongodb.uri=mongodb+srv://nadim:southeast@class.xtowejo.mongodb.net/FLICKER?appName=class

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Upload Directory - Supports custom environment variable, defaults to Linux /tmp for Cloud support
app.upload.dir=${UPLOAD_DIR:/tmp/uploads}

