
spring.data.mongodb.uri=mongodb+srv://nadim:southeast@class.xtowejo.mongodb.net/FLICKER?appName=class
spring.application.name=flicker
server.port=7777
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
app.upload.dir=C:/uploads

#app.upload.dir=./src/main/resources/static/uploads

openai.api.key=  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